//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSRI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DSRITMOBILIARIORESERVACION
    {
        public int ID_MOBILIARIORESERVACION { get; set; }
        public int ID_MOBILIARIO { get; set; }
        public int ID_RESERVACION { get; set; }

        [Display(Name = "Cantidad")]
        public int CAN_DISPONIBILIDAD { get; set; }

        public virtual DSRIFMOBILIARIO DSRIFMOBILIARIO { get; set; }
        public virtual DSRIFRESERVACION DSRIFRESERVACION { get; set; }
    }
}
