//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DSRIFUSUARIOS
    {
        public int ID_USUARIO { get; set; }
        [Required]
        [Display(Name = "Nombre de Usuario")]
        public string NOM_USUARIO { get; set; }
        [Required]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string TXT_CONTRASEÑA { get; set; }
        [Required]
        [Display(Name = "Rol")]
        public string TXT_ROL { get; set; }
        [Required]
        //[RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$" , ErrorMessage = "Correo Inválido")]
        [Display(Name = "Correo")]
        public string TXT_CORREO { get; set; }
        [Required]
        [Display(Name = "Nombrado hasta:")]
        public Nullable<System.DateTime> FEC_EXPIRACION { get; set; }
    }
}

