//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DSRIFRESERVACION
    {
        public DSRIFRESERVACION()
        {
            this.DSRITMOBILIARIORESERVACION = new HashSet<DSRITMOBILIARIORESERVACION>();
        }

        public int ID_RESERVACION { get; set; }
        [Required]
        [Display(Name = "Inmueble")]
        public int ID_INMUEBLE { get; set; }
        [Required]
        [Display(Name = "Nombre de Actividad")]
        public string NOM_ACTIVIDAD { get; set; }
        [Required]
        [Display(Name = "Fecha de Inicio")]
        [DataType(DataType.Date)]
        public System.DateTime FEC_INICIALRESERVACION { get; set; }
        [Required]
        [Display(Name = "Fecha de Finalización")]
        [DataType(DataType.Date)]
        public System.DateTime FEC_FINALRESERVACION { get; set; }
        [Required]
        [Display(Name = "Hora de Inicio")]
        [DataType(DataType.Time)]
        public System.TimeSpan HOR_INICIO { get; set; }
        [Required]
        [Display(Name = "Hora de Finalización")]
        [DataType(DataType.Time)]
        public System.TimeSpan HOR_FINAL { get; set; }
        [Required]
        [Display(Name = "Tipo de Actividad")]
        public int ID_TIPOACTIVIDAD { get; set; }
        [Required]
        [Display(Name = "Solicitante")]
        public string ID_PERSONA { get; set; }
        [Required]
        [Display(Name = "Estado")]
        public string TXT_ESTADO { get; set; }
        public int CAN_AFORO { get; set; }
        [Required]
        [Display(Name = "Teléfono")]
        public string TXT_TELEFONO { get; set; }
        [Required]
        [Display(Name = "Información extra")]
        public string TXT_EXTRA { get; set; }
        [Required]
        [Display(Name = "Objetivo")]
        public string OBJETIVO { get; set; }
        [Required]
        [Display(Name = "Personas Por Día")]
        public Nullable<int> CAN_AFORODIA { get; set; }
        [Required]
        [Display(Name = "Organizadores")]
        public string ORGANIZADOR { get; set; }

        [Display(Name = "Descripcion")]
        public string DESCRIPCION { get; set; }

        public virtual DSRIFINMUEBLE DSRIFINMUEBLE { get; set; }
        public virtual DSRIFTIPOSACTIVIDAD DSRIFTIPOSACTIVIDAD { get; set; }
        public virtual ICollection<DSRITMOBILIARIORESERVACION> DSRITMOBILIARIORESERVACION { get; set; }
    }
}
