//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DSRIFCLASIFINMUEBLE
    {
        public DSRIFCLASIFINMUEBLE()
        {
            this.DSRIFINMUEBLE = new HashSet<DSRIFINMUEBLE>();
        }

        public int ID_CLASIFINMUEBLE { get; set; }
        [Required]
        [Display(Name = "Código")]
        public string COD_CLASIFINMUEBLE { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string NOM_CLASIFINMUEBLE { get; set; }

        public virtual ICollection<DSRIFINMUEBLE> DSRIFINMUEBLE { get; set; }
    }
}
