//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DSRIFTIPOMOBILIARIO
    {
        public DSRIFTIPOMOBILIARIO()
        {
            this.DSRIFMOBILIARIO = new HashSet<DSRIFMOBILIARIO>();
        }
        [Required]
        [Display(Name = "Código")]
        public string COD_TIPOMOBILIARIO { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string NOM_TIPOMOBILIARIO { get; set; }

        public virtual ICollection<DSRIFMOBILIARIO> DSRIFMOBILIARIO { get; set; }
    }
}
