//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DSRIEntities : DbContext
    {
        public DSRIEntities()
            : base("name=DSRIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DSRIFCLASIFINMUEBLE> DSRIFCLASIFINMUEBLE { get; set; }
        public virtual DbSet<DSRIFINMUEBLE> DSRIFINMUEBLE { get; set; }
        public virtual DbSet<DSRIFMOBILIARIO> DSRIFMOBILIARIO { get; set; }
        public virtual DbSet<DSRIFRESERVACION> DSRIFRESERVACION { get; set; }
        public virtual DbSet<DSRIFTIPOMOBILIARIO> DSRIFTIPOMOBILIARIO { get; set; }
        public virtual DbSet<DSRIFTIPOSACTIVIDAD> DSRIFTIPOSACTIVIDAD { get; set; }
        public virtual DbSet<DSRIFUSUARIOS> DSRIFUSUARIOS { get; set; }
        public virtual DbSet<DSRITMOBILIARIORESERVACION> DSRITMOBILIARIORESERVACION { get; set; }
    
        public virtual ObjectResult<inmublesDisponibles_Result> inmublesDisponibles(Nullable<System.DateTime> var_fecini, Nullable<System.DateTime> var_fecfin, Nullable<System.TimeSpan> var_horaini, Nullable<System.TimeSpan> var_horafin)
        {
            var var_feciniParameter = var_fecini.HasValue ?
                new ObjectParameter("var_fecini", var_fecini) :
                new ObjectParameter("var_fecini", typeof(System.DateTime));
    
            var var_fecfinParameter = var_fecfin.HasValue ?
                new ObjectParameter("var_fecfin", var_fecfin) :
                new ObjectParameter("var_fecfin", typeof(System.DateTime));
    
            var var_horainiParameter = var_horaini.HasValue ?
                new ObjectParameter("var_horaini", var_horaini) :
                new ObjectParameter("var_horaini", typeof(System.TimeSpan));
    
            var var_horafinParameter = var_horafin.HasValue ?
                new ObjectParameter("var_horafin", var_horafin) :
                new ObjectParameter("var_horafin", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<inmublesDisponibles_Result>("inmublesDisponibles", var_feciniParameter, var_fecfinParameter, var_horainiParameter, var_horafinParameter);
        }
    
        public virtual ObjectResult<reservasUnicas_Result> reservasUnicas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reservasUnicas_Result>("reservasUnicas");
        }
    }
}
