//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DSRIFMOBILIARIO
    {
        public DSRIFMOBILIARIO()
        {
            this.DSRITMOBILIARIORESERVACION = new HashSet<DSRITMOBILIARIORESERVACION>();
        }

        public int ID_MOBILIARIO { get; set; }
        public string COD_TIPOMOBILIARIO { get; set; }
        [Required(ErrorMessage = "No se puede agregar mobiliario sin nombre")]
        [Display(Name = "Nombre")]
        public string NOM_MOBILIARIO { get; set; }
        [Display(Name = "Cantidad")]
        public int CAN_MOBILIARIO { get; set; }

        public virtual DSRIFTIPOMOBILIARIO DSRIFTIPOMOBILIARIO { get; set; }
        public virtual ICollection<DSRITMOBILIARIORESERVACION> DSRITMOBILIARIORESERVACION { get; set; }
    }
}
